/** Human-friendly display metadata for skills (Chinese names + short descriptions) */
export const SKILL_DISPLAY: Record<string, { label: string; brief: string }> = {
  "paul-graham-perspective": { label: "保罗·格雷厄姆", brief: "YC 创始人，创业、写作与产品哲学" },
  "zhang-yiming-perspective": { label: "张一鸣", brief: "字节跳动创始人，产品、组织与全球化" },
  "andrej-karpathy-perspective": { label: "卡帕西", brief: "AI 工程师，深度学习与技术教育" },
  "ilya-sutskever-perspective": { label: "伊利亚", brief: "AI 安全先驱，scaling 与研究品味" },
  "mrbeast-perspective": { label: "MrBeast", brief: "YouTube 之王，内容创造方法论" },
  "trump-perspective": { label: "特朗普", brief: "谈判、权力博弈与传播策略" },
  "steve-jobs-perspective": { label: "乔布斯", brief: "苹果创始人，产品设计与战略" },
  "elon-musk-perspective": { label: "马斯克", brief: "第一性原理，工程与成本拆解" },
  "munger-perspective": { label: "芒格", brief: "多元思维模型，投资与逆向思考" },
  "feynman-perspective": { label: "费曼", brief: "物理学家，学习方法与科学思维" },
  "naval-perspective": { label: "纳瓦尔", brief: "杠杆、特定知识与财富哲学" },
  "taleb-perspective": { label: "塔勒布", brief: "反脆弱、黑天鹅与风险管理" },
  "zhangxuefeng-perspective": { label: "张雪峰", brief: "教育选择、职业规划与阶层流动" },
  "drucker-perspective": { label: "德鲁克", brief: "管理学之父，组织效能与知识工作者" },
  "karl-marx-perspective": { label: "马克思", brief: "结构分析、矛盾分析与实践检验" },
  "laozi-perspective": { label: "老子", brief: "道法自然，反身观照与柔弱胜刚" },
  "miyamoto-perspective": { label: "宫本茂", brief: "任天堂，游戏设计与交互体验" },
  "wangyangming-perspective": { label: "王阳明", brief: "知行合一，致良知与心学实践" },
  "warren-buffett-perspective": { label: "巴菲特", brief: "价值投资，能力圈与长期主义" },

  // === Superman skills ===
  "sun-wu-perspective": { label: "孙武", brief: "孙子兵法，战略算法与不战而屈人之兵" },
  "sun-bin-perspective": { label: "孙膑", brief: "减灶诱敌，间接路线与势差作战" },
  "wu-qi-perspective": { label: "吴起", brief: "战国名将，兵法与军队激励管理" },
  "han-xin-perspective": { label: "韩信", brief: "汉初军神，背水一战与极限势差" },
  "huo-qubing-perspective": { label: "霍去病", brief: "闪电奇袭，以速决胜与极简战法" },
  "qi-jiguang-perspective": { label: "戚继光", brief: "抗倭名将，军事改革与纪律体系" },
  "zhuge-liang-perspective": { label: "诸葛亮", brief: "三国智圣，全局战略与鞠躬尽瘁" },
  "guo-jia-perspective": { label: "郭嘉", brief: "曹魏谋士，风险判断与奇谋决策" },
  "sima-yi-perspective": { label: "司马懿", brief: "三国谋略家，隐忍待机与长线博弈" },
  "zhang-liang-perspective": { label: "张良", brief: "汉初三杰，谋略辅佐与功成身退" },
  "li-shimin-perspective": { label: "李世民", brief: "唐太宗，贞观之治与用人纳谏" },
  "wu-zetian-perspective": { label: "武则天", brief: "中国唯一女皇，权力运营与政治手段" },
  "zhu-yuanzhang-perspective": { label: "朱元璋", brief: "明太祖，草根逆袭与制度铁腕" },
  "shang-yang-perspective": { label: "商鞅", brief: "法家变法，奖惩机制与制度设计" },
  "zhang-juzheng-perspective": { label: "张居正", brief: "明朝首辅，制度改革与行政效能" },
  "wang-anshi-perspective": { label: "王安石", brief: "北宋变法，财政改革与制度创新" },
  "guan-zhong-perspective": { label: "管仲", brief: "春秋第一相，富国强兵与经济治国" },
  "lu-buwei-perspective": { label: "吕不韦", brief: "商人丞相，政治投资与奇货可居" },
  "han-fei-perspective": { label: "韩非", brief: "法家集大成者，法术势三论" },
  "confucius-perspective": { label: "孔子", brief: "仁义礼智，儒家伦理与教育之道" },
  "mencius-perspective": { label: "孟子", brief: "性善论，仁政民本与浩然之气" },
  "mo-zi-perspective": { label: "墨子", brief: "兼爱非攻，平等主义与工程实用" },
  "xun-zi-perspective": { label: "荀子", brief: "性恶论，礼法并重与实用儒学" },
  "zhuang-zi-perspective": { label: "庄子", brief: "逍遥游，相对主义与自然自由" },
  "plato-perspective": { label: "柏拉图", brief: "理念论，洞穴比喻与哲人王设计" },
  "socrates-perspective": { label: "苏格拉底", brief: "苏格拉底问答法，批判性思维" },
  "nietzsche-perspective": { label: "尼采", brief: "超人哲学，权力意志与价值重估" },
  "camus-perspective": { label: "加缪", brief: "荒诞哲学，反抗与存在意义重建" },
  "sartre-perspective": { label: "萨特", brief: "存在主义，自由选择与彻底责任" },
  "newton-perspective": { label: "牛顿", brief: "万有引力与微积分，第一原理建模" },
  "leibniz-perspective": { label: "莱布尼茨", brief: "微积分、二进制与普遍符号语言" },
  "turing-perspective": { label: "图灵", brief: "计算机之父，图灵机与人工智能基础" },
  "von-neumann-perspective": { label: "冯·诺依曼", brief: "计算机架构，博弈论与极限数学" },
  "galileo-perspective": { label: "伽利略", brief: "经验验证、数学建模与真理表达" },
  "satoshi-nakamoto-perspective": { label: "中本聪", brief: "去信任共识、激励设计与协议极简" },
  "da-vinci-perspective": { label: "达·芬奇", brief: "文艺复兴巨匠，跨领域观察与创造" },
  "bian-que-perspective": { label: "扁鹊", brief: "中医诊断鼻祖，望闻问切与预防思维" },
  "guiguzi-perspective": { label: "鬼谷子", brief: "纵横鼻祖，游说术与心理博弈" },
  "su-qin-perspective": { label: "苏秦", brief: "合纵策略，多方联盟与势力平衡" },
  "fan-li-perspective": { label: "范蠡", brief: "越国谋士，商道经营与功成身退" },
  "shen-buhai-perspective": { label: "申不害", brief: "法家术治，权术管理与组织控制" },
  "shen-dao-perspective": { label: "慎到", brief: "法家势论，制度权威与无为而治" },
  "deng-xi-perspective": { label: "邓析", brief: "名辩之祖，法律辩术与逻辑推演" },
  "gongsun-long-perspective": { label: "公孙龙", brief: "白马非马，名实辩证与概念分析" },
  "zou-yan-perspective": { label: "邹衍", brief: "阴阳五行，宏大叙事与历史周期论" },
  "yan-zi-perspective": { label: "晏子", brief: "齐国名相，谏诤智慧与外交辞令" },
  "jia-yi-perspective": { label: "贾谊", brief: "西汉政论，过秦论与治乱兴衰分析" },
  "liu-bowen-perspective": { label: "刘伯温", brief: "明朝谋士，策略推演与治乱预判" },
  "yang-zhu-perspective": { label: "杨朱", brief: "贵己思想，个人主义与自我保全" },
  "xu-xing-perspective": { label: "许行", brief: "农家学说，劳动价值与自给自足" },
  "paul-perspective": { label: "保罗使徒", brief: "基督教神学奠基，信仰传播与组织建设" },
  "li-bai-perspective": { label: "李白", brief: "诗仙，浪漫主义与自由不羁精神" },
  "du-fu-perspective": { label: "杜甫", brief: "诗圣，忧国忧民与现实主义情怀" },
  "picasso-perspective": { label: "毕加索", brief: "解构重组、风格迭代与创造性破坏" },
  "su-shi-perspective": { label: "苏轼", brief: "苏东坡，全才文人与旷达人生观" },
  "caocao-perspective": { label: "曹操", brief: "魏武帝，乱世枭雄与政军一体统治" },
  "zeng-guofan-perspective": { label: "曾国藩", brief: "晚清中兴名臣，修身治学与知人善用" },
};

export function getSkillDisplay(skillId: string): { label: string; brief: string } {
  return SKILL_DISPLAY[skillId] ?? { label: skillId, brief: "" };
}
